### ISSUE TITLE
[BUG]: Commands do not load 

### ISSUE THREAD

**Issue by Kyvrixon** [IgorKowalczyk/majobot#1041]
### Environment

see https://github.com/IgorKowalczyk/majo.exe/issues/1035#issue-2400525691

### Steps To Reproduce

see https://github.com/IgorKowalczyk/majo.exe/issues/1035#issue-2400525691

### Software Version

latest commit

### Expected Behavior

see https://github.com/IgorKowalczyk/majo.exe/issues/1035#issue-2400525691

### Actual Behavior

see https://github.com/IgorKowalczyk/majo.exe/issues/1035#issue-2400525691

### Screenshots

N/A

### Severity

Critical

### Priority

High

### Type

Functional

### Reproducible

- [X] Yes
- [ ] No

### Additional Information

Refreshed my files with the latest repo (about 10 minutes ago from writing this) and the console still logs it loaded nothing (no slash commands, modals, fonts or events) and came a new error:
```
@majoexe/dashboard:deploy: TypeError: Invalid URL
@majoexe/dashboard:deploy:     at new URL (node:internal/url:797:36)
@majoexe/dashboard:deploy:     at 66307 (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\chunks\4025.js:10:3250)
@majoexe/dashboard:deploy:     at t (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\webpack-runtime.js:1:143)
@majoexe/dashboard:deploy:     at 31616 (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\app\commands\page.js:1:2265)
@majoexe/dashboard:deploy:     at t (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\webpack-runtime.js:1:143)
@majoexe/dashboard:deploy:     at t (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\app\commands\page.js:1:16230)
@majoexe/dashboard:deploy:     at C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\app\commands\page.js:1:16286
@majoexe/dashboard:deploy:     at t.X (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\webpack-runtime.js:1:1285)
@majoexe/dashboard:deploy:     at C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\app\commands\page.js:1:16243
@majoexe/dashboard:deploy:     at Object.<anonymous> (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\app\commands\page.js:1:16314) {
@majoexe/dashboard:deploy:   code: 'ERR_INVALID_URL',
@majoexe/dashboard:deploy:   input: 'null'
@majoexe/dashboard:deploy: }
@majoexe/dashboard:deploy: TypeError: Invalid URL
@majoexe/dashboard:deploy:     at new URL (node:internal/url:797:36)
@majoexe/dashboard:deploy:     at 66307 (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\chunks\4025.js:10:3250)
@majoexe/dashboard:deploy:     at t (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\webpack-runtime.js:1:143)
@majoexe/dashboard:deploy:     at 84204 (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\app\auth\error\page.js:1:2264)
@majoexe/dashboard:deploy:     at t (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\webpack-runtime.js:1:143)
@majoexe/dashboard:deploy:     at t (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\app\auth\error\page.js:1:5095)
@majoexe/dashboard:deploy:     at C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\app\auth\error\page.js:1:5146
@majoexe/dashboard:deploy:     at t.X (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\webpack-runtime.js:1:1285)
@majoexe/dashboard:deploy:     at C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\app\auth\error\page.js:1:5108
@majoexe/dashboard:deploy:     at Object.<anonymous> (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\app\auth\error\page.js:1:5174) {
@majoexe/dashboard:deploy:   code: 'ERR_INVALID_URL',
@majoexe/dashboard:deploy:   input: 'null'
@majoexe/dashboard:deploy: }
@majoexe/dashboard:deploy: TypeError: Invalid URL
@majoexe/dashboard:deploy:     at new URL (node:internal/url:797:36)
@majoexe/dashboard:deploy:     at 66307 (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\chunks\4025.js:10:3250)
@majoexe/dashboard:deploy:     at t (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\webpack-runtime.js:1:143)
@majoexe/dashboard:deploy:     at 53492 (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\app\_not-found\page.js:1:2275)
@majoexe/dashboard:deploy:     at t (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\webpack-runtime.js:1:143)
@majoexe/dashboard:deploy:     at r (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\app\_not-found\page.js:1:5069)
@majoexe/dashboard:deploy:     at C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\app\_not-found\page.js:1:5120
@majoexe/dashboard:deploy:     at t.X (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\webpack-runtime.js:1:1285)
@majoexe/dashboard:deploy:     at C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\app\_not-found\page.js:1:5082
@majoexe/dashboard:deploy:     at Object.<anonymous> (C:\Users\xxx\Desktop\majo\apps\dashboard\.next\server\app\_not-found\page.js:1:5148) {
@majoexe/dashboard:deploy:   code: 'ERR_INVALID_URL',
@majoexe/dashboard:deploy:   input: 'null'
@majoexe/dashboard:deploy: }
@majoexe/dashboard:deploy:
@majoexe/dashboard:deploy: > Build error occurred
@majoexe/dashboard:deploy: Error: Failed to collect page data for /commands
@majoexe/dashboard:deploy:     at C:\Users\xxx\Desktop\majo\node_modules\.pnpm\next@14.2.5_@babel+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\build\utils.js:1268:15
@majoexe/dashboard:deploy:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
@majoexe/dashboard:deploy:   type: 'Error'
@majoexe/dashboard:deploy: }
```
Is this an issue on my end or is it related to the last 2 commits? I have not touched anything but apply the last two commits to my codebase.

Another question, when/if these issues get fixes + ones in the future, how does deploying the dashboard on vercel work? Just set the project root at `apps/dashboard` and go for it?
*decided to open another issue instead of replying to closed issues*

**Comment by IgorKowalczyk** [comment]
CWD directory should be displayed in the console when starting the bot. It should refer to `/YOUR/PATCH/apps/bot`

![image](https://github.com/user-attachments/assets/d72b9c47-44bf-4181-895b-0aa476cf5be7)
