### ISSUE TITLE
How do i fix this?

### ISSUE THREAD

**Issue by unknowndiscorduser** [IgorKowalczyk/majobot#22]
Error: The module '/home/runner/TexturePack/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/TexturePack/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)Hint: hit control+c anytime to enter REPL.
[SQL] Connected to the MySQL server! Connection ID: 5587103
[SQL] Fetched table `logs`! Status: Success
[SQL] Fetched table `welcome`! Status: Success
[SQL] Fetched table `reputation`! Status: Success
[SQL] Fetched table `leave`! Status: Success
[SQL] Fetched table `stats`! Status: Success
/home/runner/TexturePack/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JSON NOT NULL, PRIMARY KEY (`id`))' at line 1
    at Query.<anonymous> (/home/runner/TexturePack/index.js:51:17)
    at Query.<anonymous> (/home/runner/TexturePack/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/runner/TexturePack/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/runner/TexturePack/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/runner/TexturePack/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/runner/TexturePack/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/runner/TexturePack/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/runner/TexturePack/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/runner/TexturePack/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/runner/TexturePack/node_modules/mysql/lib/Connection.js:88:28)
repl process died unexpectedly: exit status 1

**Comment by unknowndiscorduser** [comment]
sorry if its a silly question
i am dumb in using this database stuff

**Comment by unknowndiscorduser** [comment]
Using repl.it

**Comment by unknowndiscorduser** [comment]
+ can i get your discord please so that i can contact you for better :]

**Comment by IgorKowalczyk** [comment]
1. What version of Node.js are you using?
2. What version of MySQL are you using?

**Comment by unknowndiscorduser** [comment]
ahh i am not sure about mysql (please tell me how to check it)
and for node ig its 12 something (using replt.it)

**Comment by IgorKowalczyk** [comment]
Majo.exe (V12) requires Node.js 14.x and MySQL 5.7+

And do you have access to phpmyadmin or MySQL terminal?

**Comment by unknowndiscorduser** [comment]
> Majo.exe (V12) requires Node.js 14.x and MySQL 5.7+
> 
> And do you have access to phpmyadmin or MySQL terminal?

i really dont know what is that cause i am new to this... :] can i have a call with you just screen share no mic if you need

Discord : Near25#0069

**Comment by IgorKowalczyk** [comment]
I think the problem has been solved. The problem was the wrong version of Node and Mysql.
```
npm init -y && npm i --save-dev node@14 && npm config set prefix=$(pwd)/node_modules/node && export PATH=$(pwd)/node_modules/node/bin:$PATH

npm ci
```
