### ISSUE TITLE
Contact form webhook URL

### ISSUE THREAD

**Issue by AceKiller250** [IgorKowalczyk/majobot#29]
Im running my bot in repl.it as I don't have a domain and it provides a free one. I keep entering my webhook into the secrets (.env) but keep getting this error

`
> majo.exe@0.0.2 dashboard /home/runner/majobot
> node dashboard/run.js

[MAJO] Web dashboard client logged
[MAJO] Getting dashboard config file...
/home/runner/majobot/utilities/dashboard.js:6
if (!process.env.CONTACT_WEBHOOK) throw new Error("[HOST] You need to provide Discord Contact Webhook ID in .env - CONTACT_WEBHOOK_ID=YOUR_WEBHOOK_ID");
                                  ^

Error: [HOST] You need to provide Discord Contact Webhook ID in .env - CONTACT_WEBHOOK_ID=YOUR_WEBHOOK_ID
    at Object.<anonymous> (/home/runner/majobot/utilities/dashboard.js:6:41)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/majobot/dashboard/dashboard.js:22:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! majo.exe@0.0.2 dashboard: `node dashboard/run.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the majo.exe@0.0.2 dashboard script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-11-24T11_40_35_490Z-debug.log
exit status 1
 
`

**Comment by IgorKowalczyk** [comment]
Fixed in https://github.com/IgorKowalczyk/majobot/commit/2260fc76d3f249ed0d2a0a232d5c982822f17df8
