### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by NeedSomeSoftware** [IgorKowalczyk/majobot#30]
database-scripts.js Has a annoying error.
When trying to run the bot *NodeJS v16 and all the other apis working* i get this error with mySQL 

```
/home/runner/majobot-4/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JSON NOT NULL, PRIMARY KEY (`id`))' at line 1
    at Query.<anonymous> (/home/runner/majobot-4/utilities/database-scripts.js:13:17)
    at Query.<anonymous> (/home/runner/majobot-4/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/runner/majobot-4/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/runner/majobot-4/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/runner/majobot-4/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/runner/majobot-4/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/runner/majobot-4/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/runner/majobot-4/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/runner/majobot-4/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/runner/majobot-4/node_modules/mysql/lib/Connection.js:88:28)
exit status 1
```
I have switched mysql databases and i still get this error :/

**Comment by NeedSomeSoftware** [comment]
I haven't changed any code btw :/

**Comment by IgorKowalczyk** [comment]
What is the MYSQL version?

**Comment by NeedSomeSoftware** [comment]
The MySQL version is      `"mysql": "^2.18.1"`

> What is the MYSQL version?

**Comment by IgorKowalczyk** [comment]
I meant the MYSQL server version

**Comment by NeedSomeSoftware** [comment]
MySQL Version: 8.0
Server type: MySQL
Server version: 5.5.62-0ubuntu0.14.04.1 - (Ubuntu)
Protocol version: 10
Apache/2.4.18 (Ubuntu)
PHP version: 7.0.33-0ubuntu0.16.04.16

> I meant the MYSQL server version

**Comment by IgorKowalczyk** [comment]
See https://github.com/IgorKowalczyk/majobot#requirements

**Comment by NeedSomeSoftware** [comment]
> See https://github.com/IgorKowalczyk/majobot#requirements

I did downgrade MySQL Server and version and still get the same error.

**Comment by NeedSomeSoftware** [comment]
> See https://github.com/IgorKowalczyk/majobot#requirements

I have tried running the bot in replit, glitch, heroku, linode and in vscode...
I have tried all the MySQL versions and ITS STILL DOSENT WORK
I have tried diffrent MySQL servers and hosts...

**Comment by ChilledLiquid** [comment]
Your MySQL server version must be ```<=5.7```
Yours is ```5.5.62```.
Please upgrade the server version of the hosting, thank you!
